[package]
name = "creq"
version = "0.1.0"
description = "command line tool for HTTP request"
authors = ["mysangle <mysangle@gmail.com>"]
license = "MIT"

[dependencies]
reqwest = "0.3.0"
env_logger = "0.3"

